### ISSUE TITLE
Build and publish pre-packaged Ruby runtimes

### ISSUE THREAD

**Issue by ronaldtse** [tamatebako/tebako#266]
Prompt to Claude 3.7:

> Given https://github.com/tamatebako/tebako , it is a ruby packager that packages specialized Ruby version runtimes (which are patched Ruby runtimes). Assume we have a fork of the official Ruby repository at https://github.com/tamatebako/tebako-ruby that is used to build "Tebako Ruby runtimes". Write a Ruby CLI with these separate commands using Thor: (1) automatically update all existing Ruby streams (e.g. 3.4.x, 3.3.x, 3.2.x...) in our fork. (2) given a Ruby version, run the Tebako "build" command on the Ruby version to build a Tebako Ruby runtime package. (3) run Ruby tests on a built Tebako Ruby runtime package.
> 
> Then create a GHA workflow, make sure that the process is as DRY as possible, and the process can be run on GitHub Actions daily. The workflow will generate Tebako Ruby runtime packages for all Tebako-supported versions of Ruby, upload to GH releases, without replacing the runtimes that were already built (unless explicitly noted that Tebako fixes something in those runtimes).  We want the GHA builds for different Ruby versions to be done in parallel for each Ruby version (or Ruby stream) (use a GHA matrix). The GHA is responsible for the upload release process after building the Tebako Ruby runtime, the filename of the Tebako ruby runtime should indicate the detailed Ruby version and the Tebako version, and the release message should mention details of the runtime.

I'll create a Ruby CLI tool using Thor and a GitHub Actions workflow for building Tebako Ruby runtime packages. Let's break this down step by step.

## Ruby CLI Tool

First, let's create a CLI tool with Thor that can update Ruby streams, build Tebako Ruby runtimes, and run tests.

```ruby
#!/usr/bin/env ruby
# frozen_string_literal: true

require 'thor'
require 'octokit'
require 'json'
require 'fileutils'
require 'yaml'
require 'logger'

class TebakoRubyTool < Thor
  class_option :verbose, type: :boolean, default: false, desc: 'Enable verbose output'
  
  SUPPORTED_RUBY_STREAMS = %w[3.4 3.3 3.2 3.1 3.0 2.7].freeze
  TEBAKO_RUBY_REPO = 'tamatebako/tebako-ruby'
  UPSTREAM_RUBY_REPO = 'ruby/ruby'
  
  def initialize(*args)
    super
    @logger = Logger.new($stdout)
    @logger.level = options[:verbose] ? Logger::DEBUG : Logger::INFO
    @client = Octokit::Client.new(access_token: ENV['GITHUB_TOKEN'])
  end
  
  desc 'update_streams', 'Update all supported Ruby streams in the tebako-ruby fork'
  def update_streams
    @logger.info "Updating Ruby streams in #{TEBAKO_RUBY_REPO}"
    
    # Clone the repository if not already present
    clone_repo(TEBAKO_RUBY_REPO, 'tebako-ruby')
    
    Dir.chdir('tebako-ruby') do
      SUPPORTED_RUBY_STREAMS.each do |stream|
        update_stream(stream)
      end
    end
  end
  
  desc 'build VERSION', 'Build a Tebako Ruby runtime for the specified Ruby version'
  option :output_dir, type: :string, default: './build', desc: 'Directory to store the built package'
  def build(version)
    @logger.info "Building Tebako Ruby runtime for Ruby #{version}"
    validate_version(version)
    
    output_dir = File.expand_path(options[:output_dir])
    FileUtils.mkdir_p(output_dir)
    
    # Get the current Tebako version
    tebako_version = get_tebako_version
    
    # Clone the repository if not already present
    clone_repo(TEBAKO_RUBY_REPO, 'tebako-ruby')
    
    # Checkout the appropriate branch/tag for the specified Ruby version
    Dir.chdir('tebako-ruby') do
      # Detect the stream and find the right branch
      stream = version.split('.')[0..1].join('.')
      branch = "ruby_#{stream}_stable"
      
      `git checkout #{branch}`
      if $?.exitstatus != 0
        raise "Failed to checkout branch #{branch}"
      end
      
      # Build the Tebako Ruby runtime
      @logger.info "Running Tebako build process for Ruby #{version}"
      build_command = "tebako press --Ruby=#{version} --mode=runtime --output=#{output_dir}/tebako-ruby-#{version}-#{tebako_version}"
      
      @logger.debug "Executing: #{build_command}"
      system(build_command)
      
      if $?.exitstatus != 0
        raise "Failed to build Tebako Ruby runtime for Ruby #{version}"
      end
      
      @logger.info "Successfully built Tebako Ruby runtime for Ruby #{version}"
      @logger.info "Package saved to #{output_dir}/tebako-ruby-#{version}-#{tebako_version}"
    end
  end
  
  desc 'test VERSION', 'Run tests on a built Tebako Ruby runtime'
  option :package_path, type: :string, desc: 'Path to the Tebako Ruby runtime package'
  def test(version)
    @logger.info "Testing Tebako Ruby runtime for Ruby #{version}"
    validate_version(version)
    
    # Get the current Tebako version
    tebako_version = get_tebako_version
    
    # Determine the package path
    package_path = options[:package_path] || "./build/tebako-ruby-#{version}-#{tebako_version}"
    
    unless File.exist?(package_path)
      raise "Tebako Ruby runtime package not found at #{package_path}"
    end
    
    # Run tests on the package
    @logger.info "Running tests on #{package_path}"
    
    # Extract the runtime package to a temporary directory
    test_dir = "test-#{version}-#{Time.now.to_i}"
    FileUtils.mkdir_p(test_dir)
    
    # Run basic tests to verify the runtime works correctly
    @logger.info "Running Ruby version test"
    system("#{package_path} --version")
    
    if $?.exitstatus != 0
      raise "Failed to run Ruby version test"
    end
    
    # More comprehensive test
    @logger.info "Running comprehensive tests"
    test_script = "puts 'Ruby version: ' + RUBY_VERSION; puts 'Tebako test passed!'"
    system("#{package_path} -e \"#{test_script}\"")
    
    if $?.exitstatus != 0
      raise "Comprehensive test failed"
    end
    
    @logger.info "All tests passed for Tebako Ruby runtime #{version}"
    
    # Clean up
    FileUtils.rm_rf(test_dir)
  end
  
  private
  
  def clone_repo(repo, dir)
    unless Dir.exist?(dir)
      @logger.info "Cloning #{repo} into #{dir}"
      system("git clone https://github.com/#{repo}.git #{dir}")
      if $?.exitstatus != 0
        raise "Failed to clone repository #{repo}"
      end
    else
      @logger.info "Repository #{repo} already cloned, updating"
      Dir.chdir(dir) do
        system('git fetch --all')
      end
    end
  end
  
  def update_stream(stream)
    @logger.info "Updating Ruby #{stream} stream"
    
    # Get the latest tags from the upstream Ruby repository
    upstream_tags = @client.tags(UPSTREAM_RUBY_REPO)
    
    # Filter tags for the specified stream
    stream_tags = upstream_tags.select { |tag| tag.name.start_with?("v#{stream}") }
    
    if stream_tags.empty?
      @logger.warn "No tags found for Ruby stream #{stream}"
      return
    end
    
    # Sort tags by version (latest first)
    latest_tag = stream_tags.sort_by { |tag| Gem::Version.new(tag.name[1..-1]) }.last
    @logger.info "Latest tag for Ruby #{stream}: #{latest_tag.name}"
    
    # Check if we need to update our fork
    branch = "ruby_#{stream}_stable"
    
    # Create or update the branch
    if system("git rev-parse --verify #{branch} >/dev/null 2>&1")
      # Branch exists, update it
      @logger.info "Branch #{branch} exists, updating"
      system("git checkout #{branch}")
      system("git pull origin #{branch}")
    else
      # Branch doesn't exist, create it
      @logger.info "Creating branch #{branch}"
      system("git checkout -b #{branch}")
    end
    
    # Fetch the upstream tag
    system("git fetch https://github.com/#{UPSTREAM_RUBY_REPO}.git #{latest_tag.name}")
    
    # Merge the tag into our branch
    merge_message = "Merge Ruby #{latest_tag.name} into Tebako fork"
    system("git merge --no-commit --no-ff #{latest_tag.name} -m \"#{merge_message}\"")
    
    # Apply Tebako-specific patches if needed
    apply_tebako_patches(stream)
    
    # Commit the merge
    system("git commit -m \"#{merge_message}\"")
    
    # Push the changes
    system("git push origin #{branch}")
    
    @logger.info "Successfully updated Ruby #{stream} stream"
  end
  
  def apply_tebako_patches(stream)
    # Apply any Tebako-specific patches for this Ruby stream
    patches_dir = "patches/#{stream}"
    
    if Dir.exist?(patches_dir)
      Dir.glob("#{patches_dir}/*.patch").sort.each do |patch|
        @logger.info "Applying patch: #{patch}"
        system("git apply #{patch}")
        
        if $?.exitstatus != 0
          @logger.warn "Failed to apply patch: #{patch}"
        end
      end
    else
      @logger.info "No patches directory found for Ruby #{stream}"
    end
  end
  
  def validate_version(version)
    unless version =~ /^\d+\.\d+\.\d+(-\w+)?$/
      raise "Invalid Ruby version format: #{version}. Expected format: X.Y.Z or X.Y.Z-suffix"
    end
    
    stream = version.split('.')[0..1].join('.')
    unless SUPPORTED_RUBY_STREAMS.include?(stream)
      raise "Ruby stream #{stream} is not supported. Supported streams: #{SUPPORTED_RUBY_STREAMS.join(', ')}"
    end
  end
  
  def get_tebako_version
    # Get the current Tebako version from the gem or environment
    version = `tebako version`.strip
    if $?.exitstatus != 0 || version.empty?
      # Try getting from gemspec
      if File.exist?('Gemfile.lock')
        gemfile_content = File.read('Gemfile.lock')
        if gemfile_content =~ /tebako\s+\(([\d\.]+)\)/
          version = $1
        end
      end
    end
    
    version || 'unknown'
  end
end

TebakoRubyTool.start(ARGV)
```

## GitHub Actions Workflow

Now, let's create a GitHub Actions workflow that will run daily, build Tebako Ruby runtime packages for all supported Ruby versions, and upload them to GitHub releases.

```yaml
name: Build and Release Tebako Ruby Runtimes

on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: 'Force rebuild of all Tebako Ruby runtimes'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
      specific_versions:
        description: 'Comma-separated list of specific Ruby versions to build (e.g., 3.2.4,3.3.7)'
        required: false
        default: ''
        type: string

jobs:
  determine-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install octokit thor

      - name: Update Ruby streams
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ruby tebako_ruby_tool.rb update_streams --verbose

      - name: Determine versions to build
        id: set-matrix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_REBUILD: ${{ github.event.inputs.force_rebuild || 'false' }}
          SPECIFIC_VERSIONS: ${{ github.event.inputs.specific_versions }}
        run: |
          # Define the supported Ruby streams and versions
          RUBY_VERSIONS=()
          
          if [[ -n "$SPECIFIC_VERSIONS" ]]; then
            # Parse specific versions from input
            IFS=',' read -ra VERSIONS <<< "$SPECIFIC_VERSIONS"
            for version in "${VERSIONS[@]}"; do
              RUBY_VERSIONS+=("$version")
            done
          else
            # Get latest versions from each supported stream
            RUBY_VERSIONS=(
              "3.4.1"
              "3.3.7" "3.3.6" "3.3.5" "3.3.4" "3.3.3"
              "3.2.7" "3.2.6" "3.2.5" "3.2.4"
              "3.1.6"
              "3.0.7"
              "2.7.8"
            )
          fi
          
          # Get existing releases
          EXISTING_RELEASES=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/tamatebako/tebako-ruby/releases")
          
          # Get current Tebako version
          TEBAKO_VERSION=$(tebako version | tr -d '\n')
          
          # Determine which versions to build
          TO_BUILD=()
          for version in "${RUBY_VERSIONS[@]}"; do
            ASSET_NAME="tebako-ruby-${version}-${TEBAKO_VERSION}"
            if [[ "$FORCE_REBUILD" == "true" ]] || ! echo "$EXISTING_RELEASES" | grep -q "$ASSET_NAME"; then
              TO_BUILD+=("$version")
            fi
          done
          
          # Create JSON matrix for GitHub Actions
          JSON_MATRIX=$(jq -c -n --arg versions "$(printf "%s," "${TO_BUILD[@]}" | sed 's/,$//')" \
                         '{version: ($versions | split(","))}')
          
          echo "matrix=${JSON_MATRIX}" >> $GITHUB_OUTPUT
          echo "Versions to build: ${TO_BUILD[*]}"

  build:
    needs: determine-versions
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-13, windows-latest]
        version: ${{ fromJson(needs.determine-versions.outputs.matrix).version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Install Tebako
        run: |
          gem install tebako

      - name: Install dependencies
        run: |
          gem install octokit thor

      - name: Build Tebako Ruby runtime
        run: |
          ruby tebako_ruby_tool.rb build ${{ matrix.version }} --output_dir=./build --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test Tebako Ruby runtime
        run: |
          ruby tebako_ruby_tool.rb test ${{ matrix.version }} --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Tebako version
        id: tebako-version
        run: |
          TEBAKO_VERSION=$(tebako version | tr -d '\n')
          echo "tebako_version=${TEBAKO_VERSION}" >> $GITHUB_OUTPUT

      - name: Prepare artifact for upload
        id: prepare-artifact
        run: |
          OS_NAME=${{ runner.os }}
          [[ "$OS_NAME" == "macOS" ]] && OS_NAME="macos"
          [[ "$OS_NAME" == "Windows" ]] && OS_NAME="windows"
          [[ "$OS_NAME" == "Linux" ]] && OS_NAME="linux"
          
          ARCH_NAME=$(uname -m || echo "x86_64")
          [[ "$ARCH_NAME" == "x86_64" ]] && ARCH_NAME="amd64"
          [[ "$ARCH_NAME" == "aarch64" ]] && ARCH_NAME="arm64"
          
          ARTIFACT_NAME="tebako-ruby-${{ matrix.version }}-${{ steps.tebako-version.outputs.tebako_version }}-${OS_NAME}-${ARCH_NAME}"
          ARTIFACT_PATH="./build/tebako-ruby-${{ matrix.version }}-${{ steps.tebako-version.outputs.tebako_version }}"
          
          # For Windows, append .exe
          if [[ "$OS_NAME" == "windows" ]]; then
            ARTIFACT_NAME="${ARTIFACT_NAME}.exe"
            ARTIFACT_PATH="${ARTIFACT_PATH}.exe"
          fi
          
          # Rename the artifact
          mv "${ARTIFACT_PATH}" "./${ARTIFACT_NAME}"
          
          echo "artifact_name=${ARTIFACT_NAME}" >> $GITHUB_OUTPUT
          echo "artifact_path=${ARTIFACT_NAME}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.prepare-artifact.outputs.artifact_name }}
          path: ${{ steps.prepare-artifact.outputs.artifact_path }}
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: tebako-ruby-${{ steps.date.outputs.date }}
          name: Tebako Ruby Runtimes ${{ steps.date.outputs.date }}
          body: |
            Tebako Ruby runtime packages built on ${{ steps.date.outputs.date }}
            
            These packages contain Tebako-patched Ruby runtimes that can be used with Tebako for packaging Ruby applications.
            
            ## Included Ruby Versions
            
            ${{ join(matrix.version, '\n- ') }}
            
            ## Platform Support
            
            - Linux (Ubuntu 20.04, amd64)
            - macOS (macOS 13, amd64/arm64)
            - Windows (latest, amd64)
            
            ## Usage
            
            These runtime packages can be used with Tebako to create application packages:
            
            ```
            tebako press --mode=application --ref=tebako-ruby-X.Y.Z-T.V.W-OS-ARCH --root=/path/to/app --entry-point=app_entry
            ```
            
            Where X.Y.Z is the Ruby version and T.V.W is the Tebako version.
          files: ./artifacts/**/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### CLI Tool (tebako_ruby_tool.rb)

1. **Update Streams Command**: Updates all supported Ruby streams in our fork by:
   - Fetching the latest tags from the upstream Ruby repository
   - Creating or updating branches for each supported Ruby stream
   - Merging the latest changes from upstream
   - Applying any Tebako-specific patches

2. **Build Command**: Builds a Tebako Ruby runtime for a specific Ruby version:
   - Validates the Ruby version format and support
   - Clones the tebako-ruby repository if needed
   - Checks out the appropriate branch for the specified Ruby version
   - Runs the Tebako press command to build the runtime
   - Outputs the runtime package to the specified directory

3. **Test Command**: Tests a built Tebako Ruby runtime:
   - Runs basic tests to verify the runtime works correctly
   - Checks that the Ruby version is correct
   - Runs a simple script to ensure functionality

### GitHub Actions Workflow

1. **Triggering**: The workflow runs:
   - Daily at midnight UTC
   - Manually with optional parameters to force rebuilding all runtimes or specific versions

2. **Job Structure**:
   - `determine-versions`: Decides which Ruby versions need to be built
   - `build`: Builds Tebako Ruby runtimes for each version and platform in parallel
   - `release`: Creates a GitHub release with all built runtime packages

3. **Matrix Strategy**: Builds are parallelized across:
   - Different operating systems (Ubuntu, macOS, Windows)
   - Different Ruby versions

4. **Version Determination Logic**:
   - Checks existing releases to avoid rebuilding versions that already exist
   - Allows forcing rebuilds via workflow dispatch input
   - Supports building specific versions via workflow dispatch input

5. **Artifact Handling**:
   - Each built runtime is uploaded as an artifact
   - Artifacts are named with Ruby version, Tebako version, OS, and architecture
   - All artifacts are included in the final release

6. **Release Creation**:
   - Creates a new GitHub release tagged with the current date
   - Includes detailed release notes about included Ruby versions and usage instructions

This implementation provides a complete solution for automatically updating, building, testing, and releasing Tebako Ruby runtime packages while keeping the process DRY and efficient.
