### ISSUE TITLE
Use actions/checkout GitHub Action for shunit2

### ISSUE THREAD

**Issue by ronaldtse** [tamatebako/tebako#28]
https://github.com/tamatebako/tebako/blob/3027ee6ed5f63ee5000c21c4d20293bcc17e9940/.github/workflows/ubuntu-build.yml#L77

Use actions/checkout GitHub Action, like this:
```yaml
- uses: actions/checkout@v2
  with:
    repository: kward/shunit2
    path: tests/shunit2
    fetch-depth: 1
```
